### ISSUE TITLE
Atom API. Bug with parameter page greater than 2024

### ISSUE THREAD

**Issue by alexfromk** [nationalarchives/ds-caselaw-public-access-service#73]
Hello,
we are trying to work with National Archives API, with service Atom.

We got the data by requests like this:
https://caselaw.nationalarchives.gov.uk/atom.xml?page=1&order=-date
All work fine with parameter "page" since 1 to 2024, but when page became greater 2024, service return HTTP 504.
For example,
GET https://caselaw.nationalarchives.gov.uk/atom.xml?page=2025&order=-date
response with http 504.
If it is possible, to fix this bug.

With best regards. Alex Kononenko

**Comment by dragon-dxw** [comment]
We had in fact scheduled today to look at that, and we've got a fix on staging, which should go live some day soon. You should also note significantly faster load times for the atom feed pages.

**Comment by dragon-dxw** [comment]
That should be fixed on the live site now. Thank you for letting us know about the problem -- whilst we did know about it, it gives us confidence that we're working on fixing things that people care about!

**Comment by alexfromk** [comment]
Hi, thank you very much. 
I tested it, paging above 2024  work fine.
 Alex Kononenko
